name: CI

on:
  commit:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker compose up --build -d
          echo Build completed
  images:
    steps:
      -needs: build
      -name: Tag and Push docker image
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          docker tag php-backend:$GITHUB_ENV us-east1-docker.pkg.dev/h24-4d4-17/prod/php-backend:$GITHUB_ENV
          docker tag php-frontend:$GITHUB_ENV us-east1-docker.pkg.dev/h24-4d4-17/prod/php-backend:$GITHUB_ENV
          docker push us-east1-docker.pkg.dev/h24-4d4-17/prod/php-backend:$GITHUB_ENV
          docker push us-east1-docker.pkg.dev/h24-4d4-17/prod/php-frontend:$GITHUB_ENV
          echo Push completed
